import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Container, makeStyles } from '@material-ui/core';


const useStyles = makeStyles({
  container:{
    maxWidth: '500px',
    display: 'flex',
    alignItems: 'center',
  }
})


export default function Home() {
  const classes = useStyles();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container className={classes.container}>
          Home

        </Container>
      </main>
    </>
  )
}




